#!/usr/bin/env bash
# Regenerates src/boring_gen.rs from boring/scratch.br, via the project's
# ../boring.toml (project mode: `boring build --emit-rust` with no file
# argument) rather than passing scratch.br as a direct file path -- this is
# what makes boring.toml's [external_types]/[derives]/[deps] sections apply.
# Same convention as breakout-boring/boring/regen.sh.
#
# `boring build --emit-rust` now resolves and flattens every module produced
# by a `use <file>.*` (sibling-file) or `use <dep>.<module>.*` ([deps]-based
# cross-project) import directly into its single stdout stream -- fixed
# upstream in `boring` commit 77400ee ("fix(emit-rust): include cross-file/
# cross-project use modules in --emit-rust output", 2026-08-22). This
# project's own [deps]-based `use numlib.big_num.*` (in boring/scratch.br)
# is exactly the shape that fix covers: BigUint/BigInt/BigFraction now come
# through in --emit-rust's output like every other module, verified against
# this project directly (rustc- and cargo-checked) before this script was
# simplified.
#
# An older version of this script instead ran full project-mode `boring
# build` (which writes each resolved module to its own sibling
# `src/<module>.rs`, `include!()`-referenced from a generated `src/main.rs`)
# and spliced those `include!()`s back in by hand via a Python regex pass,
# to work around --emit-rust silently dropping cross-file/cross-project
# modules. No longer needed now that --emit-rust does this itself.
#
# Requires a `boring` CLI built from the `boring` repo's `main` branch (or
# any release containing the fix above). Point BORING_BIN at that binary,
# e.g.:
#
#   export BORING_BIN=../../boring/target/release/boring
#   ./regen.sh
set -euo pipefail

BORING_BIN="${BORING_BIN:-boring}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT="$PROJECT_ROOT/src/boring_gen.rs"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

(cd "$PROJECT_ROOT" && "$BORING_BIN" build --emit-rust) > "$tmp"

{
  echo "// AUTO-GENERATED by boring/regen.sh from boring/scratch.br — do not hand-edit."
  echo "// Regenerate with: (cd boring && ./regen.sh)"
  echo "#![allow(dead_code, non_snake_case, unused_imports, unused_parens, unused_mut, unused_variables)]"
  echo
  # No hand-written Rust modules remain (see README.md's "What's
  # Boring-authored vs hand-written glue" -- now empty). ScratchNumber
  # (exact arithmetic), costume_rt.rs/sound_rt.rs (zip extraction, SVG
  # rasterization), and finally sb3_loader.rs (.sb3/project.json loading,
  # the last one) were each in turn promoted to 100% Boring-authored code,
  # generated directly from boring/scratch.br + boring/sb3_loader.br (a
  # sibling file, pulled in via a bare `use sb3_loader` -- see that file's
  # own header comment) like everything else in this crate. `Sb3Project`
  # and friends stay visible to `tests/*.rs` (a separate crate) because
  # every such type is declared `pub struct`/`pub enum` directly in
  # `sb3_loader.br` -- no `mod`/`pub use` prelude needed here to re-export
  # them (confirmed necessary by a real E0603 "private struct" error from
  # tests/costumes.rs when an earlier hand-written version of this wasn't
  # `pub`).
  cat "$tmp"
} > "$OUT"

echo "wrote $OUT"
