//! End-to-end test for Event: broadcasts (`event_broadcast`,
//! `event_broadcastandwait`, `event_whenbroadcastreceived`). Fixture
//! generated by a small script (not checked in) into
//! `assets/broadcasts.json` -- summarized script logic across three targets
//! (broadcasts are project-wide, not scoped to one sprite):
//!
//! ```text
//! Sprite1, when green flag clicked:
//!   broadcast "go"                 (non-waiting)
//!   broadcast "go2" and wait
//!   set done to "true"
//! Sprite1, when I receive "go":  set receivedA to "true"
//! Sprite2, when I receive "go":  set receivedB to "true"
//! Sprite2, when I receive "go2": set receivedC to "true"
//! ```
//!
//! Exercises: a receiver on the SAME sprite as the broadcaster ("go" ->
//! receivedA), a receiver on a DIFFERENT sprite (project-wide fan-out --
//! "go" -> receivedB), both `broadcast` and `broadcast and wait` actually
//! running their receiver(s) before the calling script's own next statement
//! sees any effect (`done` only becomes "true" after `go2`'s receiver has
//! already set `receivedC`), and that the broadcasting script's own state
//! survives past the broadcast (`done` gets set correctly afterward).

use scratch_boring::run_greenflag_and_report_json;
use std::sync::Arc;

#[test]
fn broadcast_and_broadcast_and_wait_reach_all_matching_receivers() {
    let path: Arc<str> = Arc::from("assets/broadcasts.json");
    let get = |name: &'static str| run_greenflag_and_report_json(path.clone(), Arc::from(name));

    assert_eq!(get("receivedA").as_ref(), "true", "same-sprite \"go\" receiver should have run");
    assert_eq!(get("receivedB").as_ref(), "true", "other-sprite \"go\" receiver should have run (project-wide fan-out)");
    assert_eq!(get("receivedC").as_ref(), "true", "\"go2\" (broadcast and wait) receiver should have run");
    assert_eq!(get("done").as_ref(), "true", "the broadcasting script itself should continue and finish afterward");
}
