//! End-to-end test for `event_whenthisspriteclicked` -- the single
//! largest opcode left after the graphic-effects round (11 occurrences in
//! one of the three tracked real projects). Edge-triggered against real
//! Bevy input (`ButtonInput<MouseButton>.just_pressed`, same primitive
//! `check_key_press_hats` uses for keys) *and* an AABB hit test against
//! the hat's own owning sprite (`touching_point`, the exact same
//! bounding-box math `sensing_touchingobject`'s mouse-touching case
//! already uses -- see `ClickHat`'s own doc comment in runtime.br).
//!
//! `assets/click_hats.json` (fixture generated by a small script, not
//! checked in) -- two sprites, no real `.sb3` costume assets (so both get
//! the 40x40 placeholder box, half-width/half-height 20):
//!
//! ```text
//! A @ (0, 0):   when this sprite clicked -> set clicked_a to 1
//! B @ (200, 0): when this sprite clicked -> set clicked_b to 1
//! ```
//!
//! No `WindowPlugin` (headless `MinimalPlugins`, same as `tests/input.rs`)
//! -- `MouseState` never gets synced from a real window in that
//! configuration (`sync_mouse_state`'s own doc comment), so this sets it
//! directly, the same "manual resource mutation between ticks" technique
//! `tests/scheduler.rs` uses for `ScratchTimer.elapsed`.

use bevy::input::ButtonInput;
use bevy::prelude::*;
use scratch_boring::{
    check_click_hats, run_pending_threads, setup_scratch_project, stage_var_value,
    sync_keyboard_state, sync_mouse_state, MouseState, ProjectPath, Vars,
};
use std::sync::Arc;

fn test_app() -> App {
    let path: Arc<str> = Arc::from("assets/click_hats.json");
    let mut app = App::new();
    app.add_plugins(MinimalPlugins)
        .add_plugins((AssetPlugin::default(), ImagePlugin::default()))
        .insert_resource(ButtonInput::<KeyCode>::default())
        .insert_resource(ButtonInput::<MouseButton>::default())
        .insert_resource(ProjectPath { path })
        .add_systems(Startup, setup_scratch_project)
        .add_systems(
            Update,
            (sync_keyboard_state, sync_mouse_state, check_click_hats, run_pending_threads).chain(),
        );
    app
}

fn var(app: &mut App, name: &'static str) -> Arc<str> {
    let vars = app.world().resource::<Vars>().clone();
    stage_var_value(Arc::from("assets/click_hats.json"), vars, Arc::from(name))
}

#[test]
fn clicking_a_sprite_fires_only_that_sprites_own_click_hat() {
    let mut app = test_app();

    // Tick 1: nothing pressed yet -- neither hat should have fired.
    app.update();
    assert_ne!(var(&mut app, "clicked_a").as_ref(), "1", "no click yet");
    assert_ne!(var(&mut app, "clicked_b").as_ref(), "1", "no click yet");

    // Mouse starts at the headless-fixed origin (0, 0) -- exactly A's own
    // position, well inside its 40x40 box, well outside B's (at 200, 0).
    // Press the button: A's click hat should fire, B's should not.
    app.world_mut().resource_mut::<ButtonInput<MouseButton>>().press(MouseButton::Left);
    app.update();
    assert_eq!(var(&mut app, "clicked_a").as_ref(), "1", "clicking at A's own position should fire A's click hat");
    assert_ne!(var(&mut app, "clicked_b").as_ref(), "1", "B is far away (200, 0) -- its own click hat must not fire");

    // Release, then move the mouse onto B and click again -- B's hat
    // should now fire too (edge-triggered: releasing and re-pressing is
    // required, holding the button down must not keep re-firing).
    app.world_mut().resource_mut::<ButtonInput<MouseButton>>().release(MouseButton::Left);
    app.update();
    app.world_mut().resource_mut::<MouseState>().x = 200.0;
    app.world_mut().resource_mut::<MouseState>().y = 0.0;
    app.world_mut().resource_mut::<ButtonInput<MouseButton>>().press(MouseButton::Left);
    app.update();
    assert_eq!(var(&mut app, "clicked_b").as_ref(), "1", "clicking at B's own position should fire B's click hat");
}
