//! End-to-end test for Control: `control_if`, `control_if_else`, and
//! `control_stop`, plus the `operator_gt`/`operator_lt` comparisons needed
//! to write a real (non-trivial) condition. Fixture generated by a small
//! script (not checked in) into `assets/control_flow.json` -- see that
//! file for the exact block graph; summarized script logic:
//!
//! ```text
//! when green flag clicked:
//!   set a to 0;  if (10 > 3): set a to 1  else: set a to 2
//!   set b to 0;  if (3 > 10): set b to 2  else: set b to 1
//!   set c to 0;  if (2 < 5):  set c to 1
//!   set e to 7;  if (1 > 100): set e to 999
//!   set d to 0;  if (100 > 1): stop this script
//!               set d to 99   # unreachable if the stop above fired
//! ```
//!
//! `d` is the load-bearing assertion: it only stays `0` if `control_stop`
//! actually unwinds `exec`'s statement loop rather than merely being a
//! silent no-op (which would let `set d to 99` run right after it).

use scratch_boring::run_greenflag_and_report_json;
use std::sync::Arc;

#[test]
fn if_else_and_stop_this_script() {
    let path: Arc<str> = Arc::from("assets/control_flow.json");
    let get = |name: &'static str| run_greenflag_and_report_json(path.clone(), Arc::from(name));

    assert_eq!(get("a").as_ref(), "1", "10 > 3 is true: the then-branch should have run");
    assert_eq!(get("b").as_ref(), "1", "3 > 10 is false: the else-branch should have run");
    assert_eq!(get("c").as_ref(), "1", "2 < 5 is true: the (else-less) if-body should have run");
    assert_eq!(get("e").as_ref(), "7", "1 > 100 is false: the (else-less) if-body must NOT have run");
    assert_eq!(
        get("d").as_ref(),
        "0",
        "100 > 1 is true -> `stop this script` should fire and prevent `set d to 99` from ever running"
    );
}
