//! End-to-end test for costume switching (`looks_switchcostumeto`/
//! `looks_nextcostume`/`looks_costume`/`looks_costumenumbername`) --
//! added once a real scratch.mit.edu project (fetched to validate this
//! project end to end) showed it was the single largest remaining Looks
//! gap after show/hide/size landed.
//!
//! Fixture generated by a small script (not checked in) into
//! `assets/costume_switch.json` -- Sprite1 has three costumes, `"a"`,
//! `"b"`, `"c"` (indices 0, 1, 2), starting on `"a"`:
//!
//! ```text
//! when green flag clicked:
//!   switch costume to "c"              -> index 2
//!   set result1 to (costume number)    -> 3
//!   next costume                       -> wraps 2 -> 0
//!   set result2 to (costume number)    -> 1
//!   switch costume to 2                -> 1-based numeric index -> 0-based 1
//!   set result3 to (costume number)    -> 2
//!   switch costume to "nonexistent"    -> no match; not numeric either,
//!                                          but real Scratch's own
//!                                          `Cast.toNumber` never fails --
//!                                          it coerces to 0 the same way
//!                                          `to_num()` does here, giving
//!                                          `0 - 1 = -1`, wrapped to the
//!                                          *last* costume, index 2
//!   set result4 to (costume number)    -> 3 (NOT a no-op -- see above)
//! ```
//!
//! `tests/looks_visual.rs`'s show/hide/size tests already establish the
//! real-Bevy-`Sprite`-swap pattern for Looks visual state generally; this
//! file adds the `TargetCostumeHandles` pre-loading check specifically,
//! against the real `Fibonacci_1.sb3` fixture (the only fixture already
//! in this repo with more than one real costume asset -- see
//! `tests/costumes.rs`).

use bevy::input::ButtonInput;
use bevy::prelude::*;
use scratch_boring::{
    run_greenflag_and_report_json, setup_scratch_project, ProjectPath, ScratchSprite,
    TargetCostumeHandles,
};
use std::sync::Arc;

#[test]
fn switchcostumeto_by_name_and_number_and_nextcostume_wrap_correctly() {
    let path: Arc<str> = Arc::from("assets/costume_switch.json");
    let get = |name: &'static str| run_greenflag_and_report_json(path.clone(), Arc::from(name));

    assert_eq!(get("result1").as_ref(), "3", "switch costume to \"c\" (index 2, 1-based 3)");
    assert_eq!(get("result2").as_ref(), "1", "next costume wraps from the last costume back to the first");
    assert_eq!(get("result3").as_ref(), "2", "switch costume to 2 (a numeric 1-based index)");
    assert_eq!(
        get("result4").as_ref(),
        "3",
        "switch costume to \"nonexistent\" matches no costume name, but real Scratch's Cast.toNumber never fails -- it coerces to 0, giving 0-1=-1, wrapped to the last costume (not a no-op)"
    );
}

#[test]
fn every_real_costume_gets_pre_loaded_as_a_real_bevy_handle() {
    let path: Arc<str> = Arc::from("assets/Fibonacci_1.sb3");
    let mut app = App::new();
    app.add_plugins(MinimalPlugins)
        .add_plugins((AssetPlugin::default(), ImagePlugin::default()))
        .insert_resource(ButtonInput::<KeyCode>::default())
        .insert_resource(ButtonInput::<MouseButton>::default())
        .insert_resource(ProjectPath { path })
        .add_systems(Startup, setup_scratch_project);
    app.update();

    let world = app.world_mut();
    let mut query = world.query::<(&ScratchSprite, &TargetCostumeHandles)>();
    let (_, handles) = query
        .iter(world)
        .find(|(sprite, _)| sprite.target_id.as_ref() == "Sprite1")
        .expect("Sprite1 should have a ScratchSprite+TargetCostumeHandles entity");
    assert_eq!(
        handles.handles.len(),
        2,
        "Fibonacci_1.sb3's Sprite1 has exactly two real costumes (costume1, costume2) -- both should be pre-loaded, not just the currently-selected one"
    );
}
