//! End-to-end test for Data: lists (`data_addtolist`/`data_deleteoflist`/
//! `data_insertatlist`/`data_replaceitemoflist`/`data_lengthoflist`/
//! `data_itemoflist`/`data_itemnumoflist`/`data_listcontainsitem`) and
//! `data_changevariableby`. Fixture generated by a small script (not
//! checked in) into `assets/data_lists.json` -- summarized script logic:
//!
//! ```text
//! myList starts as ["a", "b", "c"]; counter starts at 10.
//! when green flag clicked:
//!   add "d" to myList                        -> ["a","b","c","d"]
//!   delete 2 of myList                       -> ["a","c","d"]        (removes "b")
//!   insert "x" at 1 of myList                -> ["x","a","c","d"]
//!   replace item 3 of myList with "z"        -> ["x","a","z","d"]
//!   set len to (length of myList)             -> 4
//!   set first_item to (item 1 of myList)      -> "x"
//!   set idx to (item # of "z" in myList)      -> 3
//!   set has_d to (myList contains "d"?)       -> true
//!   change counter by 5                       -> 15
//! ```

use scratch_boring::{run_greenflag_and_report_json, run_greenflag_and_report_list_json};
use std::sync::Arc;

#[test]
fn list_mutation_and_query_blocks() {
    let path: Arc<str> = Arc::from("assets/data_lists.json");
    let get = |name: &'static str| run_greenflag_and_report_json(path.clone(), Arc::from(name));

    assert_eq!(get("len").as_ref(), "4", "add + insert - delete = 4 items");
    assert_eq!(get("first_item").as_ref(), "x", "item 1 after insert should be \"x\"");
    assert_eq!(get("idx").as_ref(), "3", "\"z\" (from the replace) should be at position 3");
    assert_eq!(get("has_d").as_ref(), "true", "\"d\" (added first) should still be in the list");
    assert_eq!(get("counter").as_ref(), "15", "10 + 5 via data_changevariableby");

    let contents = run_greenflag_and_report_list_json(path, Arc::from("myList"));
    assert_eq!(
        contents.as_ref(),
        "x,a,z,d",
        "final list order after add/delete/insert/replace"
    );
}
