//! End-to-end test for `looks_seteffectto`/`looks_changeeffectby`/
//! `looks_cleargraphiceffects` -- scoped to the one graphic effect this
//! project actually renders, `ghost` (real Scratch's own 0-100 range,
//! mapped onto `Sprite.color`'s real alpha channel: 0 = opaque, 100 =
//! fully invisible). See `LooksState.ghost`'s own doc comment
//! (runtime.br) for why the other six effects (color/fisheye/whirl/
//! pixelate/mosaic/brightness) are a real, deliberately narrow gap
//! rather than a partial job: real Scratch has no reporter for *any*
//! graphic effect's value, so there's nothing to observably get wrong by
//! not tracking them.
//!
//! No reporter exists to check this headless the way `looks_size` can
//! (`tests/looks_visual.rs`), so this checks the real rendered `Sprite.
//! color` alpha directly, same pattern as that file's own `looks_hide`
//! test. Four separate single-sprite fixtures (generated by a small
//! script, not checked in) rather than one fixture with four sprites --
//! `setup_scratch_project`/`build_greenflag_script` only ever start *one*
//! green-flag script per project (the first one found across all
//! targets), not one per sprite, so four independent sprite scripts in
//! one project would only ever have run one of them (found the hard way,
//! debugging a first draft of this test that got that wrong):
//!
//! ```text
//! graphic_effect_set.json:         set ghost effect to 40                    -> alpha 0.6
//! graphic_effect_clamp_high.json:  set to 40; change by 70 (-> 110)          -> clamped 100, alpha 0.0
//! graphic_effect_clamp_low.json:   set to 40; change by -1000                -> clamped 0, alpha 1.0
//! graphic_effect_clear.json:       set to 50; clear graphic effects         -> reset 0, alpha 1.0
//! ```

use bevy::input::ButtonInput;
use bevy::prelude::*;
use scratch_boring::{
    run_pending_threads, setup_scratch_project, sync_ghost_effect_from_looks_states,
    sync_keyboard_state, sync_mouse_state, ProjectPath, ScratchSprite,
};
use std::sync::Arc;

fn sprite1_alpha_after_greenflag(fixture: &str) -> f32 {
    let path: Arc<str> = Arc::from(fixture);
    let mut app = App::new();
    app.add_plugins(MinimalPlugins)
        .add_plugins((AssetPlugin::default(), ImagePlugin::default()))
        .insert_resource(ButtonInput::<KeyCode>::default())
        .insert_resource(ButtonInput::<MouseButton>::default())
        .insert_resource(ProjectPath { path })
        .add_systems(Startup, setup_scratch_project)
        .add_systems(
            Update,
            (
                sync_keyboard_state,
                sync_mouse_state,
                run_pending_threads,
                sync_ghost_effect_from_looks_states,
            )
                .chain(),
        );
    // None of SetGraphicEffectTo/ChangeGraphicEffectBy/ClearGraphicEffects
    // ever yields (no wait involved) -- every fixture's whole script
    // finishes within this one tick.
    app.update();

    let world = app.world_mut();
    let mut query = world.query::<(&ScratchSprite, &Sprite)>();
    let (_, sprite) = query
        .iter(world)
        .find(|(s, _)| s.target_id.as_ref() == "Sprite1")
        .expect("Sprite1 should have a ScratchSprite+Sprite entity");
    sprite.color.alpha()
}

#[test]
fn set_graphic_effect_to_sets_the_real_sprite_alpha() {
    let alpha = sprite1_alpha_after_greenflag("assets/graphic_effect_set.json");
    assert!((alpha - 0.6).abs() < 0.001, "ghost 40 should be alpha 0.6 (1 - 40/100), got {alpha}");
}

#[test]
fn change_graphic_effect_by_clamps_at_the_high_end() {
    let alpha = sprite1_alpha_after_greenflag("assets/graphic_effect_clamp_high.json");
    assert!((alpha - 0.0).abs() < 0.001, "40 + 70 = 110, clamped to 100 -> fully invisible (alpha 0), got {alpha}");
}

#[test]
fn change_graphic_effect_by_clamps_at_the_low_end() {
    let alpha = sprite1_alpha_after_greenflag("assets/graphic_effect_clamp_low.json");
    assert!((alpha - 1.0).abs() < 0.001, "40 - 1000 clamps to 0 -> fully opaque (alpha 1), got {alpha}");
}

#[test]
fn clear_graphic_effects_resets_ghost_back_to_fully_opaque() {
    let alpha = sprite1_alpha_after_greenflag("assets/graphic_effect_clear.json");
    assert!((alpha - 1.0).abs() < 0.001, "clear graphic effects should reset ghost back to 0 -> alpha 1, got {alpha}");
}
