//! End-to-end test for Sensing's keyboard/mouse blocks
//! (`sensing_keypressed`/`sensing_mousex`/`sensing_mousey`/
//! `sensing_mousedown`) and the `event_whenkeypressed` hat. Fixture
//! generated by a small script (not checked in) into `assets/input.json`:
//!
//! ```text
//! Sprite1, when green flag clicked:  set greenflagRan to "true"
//! Sprite1, when space key pressed:
//!   set spaceHat to "true"
//!   set spaceReporterAtHatTime to (key space pressed?)
//! ```
//!
//! Headless (`MinimalPlugins`, no window) -- `ButtonInput<KeyCode>`/
//! `ButtonInput<MouseButton>` are inserted manually rather than via
//! `InputPlugin` (which also runs event-processing systems this test
//! doesn't need); simulating a press is a direct `.press(...)` call on that
//! resource between two `app.update()` calls, same technique
//! `breakout-boring`'s own headless tests use for `Time::advance_by`.
//!
//! Exercises: `event_whenkeypressed` does NOT fire before its key is
//! pressed (real Scratch's own edge-triggered semantics -- there's no
//! implicit "run once at start" the way `event_whenflagclicked` has), it
//! DOES fire the tick the key transitions to pressed, and
//! `sensing_keypressed` (level-triggered) reads "true" for that same key on
//! that same tick -- i.e. `sync_keyboard_state` genuinely runs before
//! `run_pending_threads` in the same `Update` tick, not one tick behind.
//! Also proves `sync_mouse_state`'s `Single<Window&>` doesn't panic in a
//! window-less headless app (a real, deliberately-checked risk -- see
//! `sync_mouse_state`'s own doc comment).

use bevy::input::ButtonInput;
use bevy::prelude::*;
use scratch_boring::{
    check_key_press_hats, run_pending_threads, setup_scratch_project, stage_var_value,
    sync_keyboard_state, sync_mouse_state, ProjectPath, Vars,
};
use std::sync::Arc;

fn test_app() -> App {
    let path: Arc<str> = Arc::from("assets/input.json");
    let mut app = App::new();
    app.add_plugins(MinimalPlugins)
        .add_plugins((AssetPlugin::default(), ImagePlugin::default()))
        // Manual resource insertion instead of `InputPlugin` -- this test
        // only needs to simulate a press via `.press(...)`, not real
        // OS-event processing.
        .insert_resource(ButtonInput::<KeyCode>::default())
        .insert_resource(ButtonInput::<MouseButton>::default())
        .insert_resource(ProjectPath { path })
        .add_systems(Startup, setup_scratch_project)
        .add_systems(
            Update,
            (
                sync_keyboard_state,
                sync_mouse_state,
                check_key_press_hats,
                run_pending_threads,
            )
                .chain(),
        );
    app
}

fn var(app: &mut App, name: &'static str) -> Arc<str> {
    let vars = app.world().resource::<Vars>().clone();
    stage_var_value(Arc::from("assets/input.json"), vars, Arc::from(name))
}

#[test]
fn key_press_hat_is_edge_triggered_and_reporter_matches_same_tick() {
    let mut app = test_app();

    // First tick: Startup runs the green-flag script; no key has been
    // pressed yet.
    app.update();
    assert_eq!(var(&mut app, "greenflagRan").as_ref(), "true");
    assert_ne!(var(&mut app, "spaceHat").as_ref(), "true", "hat must not fire before its key is ever pressed");

    // Simulate pressing space, then let one more tick run.
    app.world_mut()
        .resource_mut::<ButtonInput<KeyCode>>()
        .press(KeyCode::Space);
    app.update();

    assert_eq!(var(&mut app, "spaceHat").as_ref(), "true", "event_whenkeypressed should have fired this tick");
    assert_eq!(
        var(&mut app, "spaceReporterAtHatTime").as_ref(),
        "true",
        "sensing_keypressed should already read true within the same tick the hat fired"
    );
}

#[test]
fn key_press_hat_does_not_refire_while_key_stays_held() {
    let mut app = test_app();
    app.update();
    app.world_mut()
        .resource_mut::<ButtonInput<KeyCode>>()
        .press(KeyCode::Space);
    app.update();
    assert_eq!(var(&mut app, "spaceHat").as_ref(), "true");

    // Bevy's ButtonInput clears "just pressed" flags at the start of each
    // real frame's input processing in a full app, but with no InputPlugin
    // driving that here, `just_pressed` state persists across our manual
    // `app.update()` calls unless cleared -- clear it explicitly to
    // simulate "still held, not a fresh press" for tick 3, matching what a
    // real running app would naturally do each frame.
    app.world_mut()
        .resource_mut::<ButtonInput<KeyCode>>()
        .clear_just_pressed(KeyCode::Space);
    app.update();
    // No new hat run should have queued (nothing to directly assert on
    // beyond "no panic and the value is still exactly what it was" --
    // there's no re-run side effect that would change any variable, so
    // this mostly proves check_key_press_hats correctly stops matching
    // once `just_pressed` is cleared).
    assert_eq!(var(&mut app, "spaceHat").as_ref(), "true");
}
