//! End-to-end test for `looks_gotofrontback` -- the single largest
//! remaining opcode after the click-hats round (8 occurrences in one of
//! the three tracked real projects). No reporter exists to check this
//! headless (real Scratch has none either), so this checks the real
//! `Transform.translation.z` `sync_z_from_layer_orders` writes directly,
//! same pattern as `tests/graphic_effects.rs`'s own `Sprite.color` check.
//!
//! `assets/layering_front.json`/`assets/layering_back.json` (fixtures
//! generated by a small script, not checked in) -- three sprites, A/B/C,
//! with on-disk `layerOrder` 1/2/3 respectively (A behind, C in front):
//!
//! ```text
//! layering_front.json: A's own green-flag script does "go to front"
//!   -> A should end up above both B and C
//! layering_back.json:  C's own green-flag script does "go to back"
//!   -> C should end up below both A and B
//! ```

use bevy::input::ButtonInput;
use bevy::prelude::*;
use scratch_boring::{
    run_pending_threads, setup_scratch_project, sync_keyboard_state, sync_mouse_state,
    sync_z_from_layer_orders, ProjectPath, ScratchSprite,
};
use std::sync::Arc;

fn z_values(fixture: &str) -> std::collections::HashMap<String, f32> {
    let path: Arc<str> = Arc::from(fixture);
    let mut app = App::new();
    app.add_plugins(MinimalPlugins)
        .add_plugins((AssetPlugin::default(), ImagePlugin::default()))
        .insert_resource(ButtonInput::<KeyCode>::default())
        .insert_resource(ButtonInput::<MouseButton>::default())
        .insert_resource(ProjectPath { path })
        .add_systems(Startup, setup_scratch_project)
        .add_systems(
            Update,
            (sync_keyboard_state, sync_mouse_state, run_pending_threads, sync_z_from_layer_orders).chain(),
        );
    app.update();

    let world = app.world_mut();
    let mut query = world.query::<(&ScratchSprite, &Transform)>();
    query
        .iter(world)
        .map(|(s, t)| (s.target_id.to_string(), t.translation.z))
        .collect()
}

#[test]
fn go_to_front_ends_up_above_every_other_sprite() {
    let z = z_values("assets/layering_front.json");
    assert!(z["A"] > z["B"], "A went to front, should end up above B: {z:?}");
    assert!(z["A"] > z["C"], "A went to front, should end up above C (which started furthest front): {z:?}");
}

#[test]
fn go_to_back_ends_up_below_every_other_sprite() {
    let z = z_values("assets/layering_back.json");
    assert!(z["C"] < z["A"], "C went to back, should end up below A: {z:?}");
    assert!(z["C"] < z["B"], "C went to back, should end up below B: {z:?}");
}
