//! End-to-end test for Looks' `looks_say`/`looks_think` (speech/thought
//! bubbles). Fixture generated by a small script (not checked in) into
//! `assets/looks.json`:
//!
//! ```text
//! Sprite1, when green flag clicked:
//!   say "Hello!"
//!   think "Hmm..."
//! ```
//!
//! Both run in the same script, so the final bubble text is "Hmm..." (the
//! `think` overwrites the earlier `say` on the same target) -- this proves
//! `SpeechBubbles.set` correctly replaces the previous entry rather than,
//! say, only ever writing once.

use scratch_boring::run_greenflag_and_report_speech_json;
use std::sync::Arc;

#[test]
fn think_after_say_overwrites_the_bubble_on_the_same_target() {
    let path: Arc<str> = Arc::from("assets/looks.json");
    let text = run_greenflag_and_report_speech_json(path, Arc::from("Sprite1"));
    assert_eq!(text.as_ref(), "Hmm...");
}

#[test]
fn a_target_that_never_spoke_reports_an_empty_bubble() {
    let path: Arc<str> = Arc::from("assets/looks.json");
    let text = run_greenflag_and_report_speech_json(path, Arc::from("Stage"));
    assert_eq!(text.as_ref(), "");
}
