//! End-to-end test for Looks' visibility/size state (`looks_show`/
//! `looks_hide`/`looks_setsizeto`/`looks_changesizeby`/`looks_size`) --
//! added once a real scratch.mit.edu project (fetched to validate this
//! project end to end) showed these among the biggest remaining
//! real-world compatibility gaps, right after the scheduler landed.
//!
//! Fixtures generated by a small script (not checked in):
//!
//! ```text
//! assets/size.json:
//!   Sprite1, when green flag clicked:
//!     set size to 50; change size by 25; set result to (size)   -> 75
//!
//! assets/show_hide.json:
//!   Sprite1, when green flag clicked: hide
//!   Sprite2: no scripts at all -- stays at its own saved-visible default
//! ```

use bevy::input::ButtonInput;
use bevy::prelude::*;
use scratch_boring::{
    run_greenflag_and_report_json, run_pending_threads, setup_scratch_project, sync_keyboard_state,
    sync_mouse_state, sync_visibility_and_size_from_looks_states, ProjectPath, ScratchSprite,
};
use std::sync::Arc;

#[test]
fn looks_size_reporter_reflects_setsizeto_and_changesizeby() {
    let path: Arc<str> = Arc::from("assets/size.json");
    let result = run_greenflag_and_report_json(path, Arc::from("result"));
    assert_eq!(result.as_ref(), "75", "set size to 50, then change by 25");
}

fn show_hide_test_app() -> App {
    let path: Arc<str> = Arc::from("assets/show_hide.json");
    let mut app = App::new();
    app.add_plugins(MinimalPlugins)
        .add_plugins((AssetPlugin::default(), ImagePlugin::default()))
        .insert_resource(ButtonInput::<KeyCode>::default())
        .insert_resource(ButtonInput::<MouseButton>::default())
        .insert_resource(ProjectPath { path })
        .add_systems(Startup, setup_scratch_project)
        .add_systems(
            Update,
            (
                sync_keyboard_state,
                sync_mouse_state,
                run_pending_threads,
                sync_visibility_and_size_from_looks_states,
            )
                .chain(),
        );
    app
}

#[test]
fn looks_hide_sets_real_visibility_hidden_on_the_sprites_own_entity() {
    let mut app = show_hide_test_app();
    app.update();

    let world = app.world_mut();
    let mut query = world.query::<(&ScratchSprite, &Visibility)>();
    let found: Vec<(String, Visibility)> = query
        .iter(world)
        .map(|(sprite, vis)| (sprite.target_id.to_string(), *vis))
        .collect();

    let sprite1 = found
        .iter()
        .find(|(id, _)| id == "Sprite1")
        .expect("Sprite1 should have a ScratchSprite+Visibility entity");
    assert_eq!(sprite1.1, Visibility::Hidden, "Sprite1's own green-flag script calls hide");

    let sprite2 = found
        .iter()
        .find(|(id, _)| id == "Sprite2")
        .expect("Sprite2 should have a ScratchSprite+Visibility entity");
    assert_eq!(sprite2.1, Visibility::Visible, "Sprite2 has no scripts at all -- stays at its own saved-visible default");
}
