//! End-to-end test for `motion_goto`/`motion_goto_menu` and
//! `operator_round`. `assets/motion_goto.json` (fixture generated by a
//! small script, not checked in) -- A starts at (0,0), B is stationary at
//! (50,60); A's own green-flag script:
//!
//! ```text
//! go to B                          -> A's position becomes (50, 60)
//! go to "mouse pointer"            -> (headless-fixed mouse at (0,0))
//! go to "random position"          -> some point within the stage bounds
//! round(-2.5)                      -> -2 (Math.round-style half-up, not -3)
//! ```

use scratch_boring::run_greenflag_and_report_json;
use std::sync::Arc;

#[test]
fn motion_goto_resolves_mouse_random_and_sprite_name_targets() {
    let path: Arc<str> = Arc::from("assets/motion_goto.json");
    let get = |name: &'static str| run_greenflag_and_report_json(path.clone(), Arc::from(name));

    assert_eq!(get("result_x_after_b").as_ref(), "50", "go to B should move A to B's own x");
    assert_eq!(get("result_y_after_b").as_ref(), "60", "go to B should move A to B's own y");

    assert_eq!(get("result_x_after_mouse").as_ref(), "0", "headless mouse is always fixed at (0,0)");
    assert_eq!(get("result_y_after_mouse").as_ref(), "0", "headless mouse is always fixed at (0,0)");

    let rx: f64 = get("result_x_after_random").parse().expect("a real number");
    let ry: f64 = get("result_y_after_random").parse().expect("a real number");
    assert!((-240.0..=240.0).contains(&rx), "random x should land within the real stage bounds, got {rx}");
    assert!((-180.0..=180.0).contains(&ry), "random y should land within the real stage bounds, got {ry}");

    assert_eq!(get("result_round").as_ref(), "-2", "Math.round(-2.5) == -2 (round half up, toward +infinity), not -3");
}
