//! End-to-end test for the Motion category (`motion_movesteps`,
//! `motion_turnright`, `motion_gotoxy`, `motion_changexby`/`changeyby`,
//! `motion_pointindirection`, `motion_xposition`). Fixture generated by a
//! small script (not checked in) into `assets/motion.json` -- one sprite,
//! default direction 90 (facing right), green-flag script:
//!
//! ```text
//! move 10 steps            (direction 90: dx=10, dy=~0)
//! turn right 90 degrees     (direction -> 180)
//! move 5 steps              (direction 180: dx=~0, dy=-5)
//! go to x: 100 y: 50        (overwrites the above -- clears any float noise
//!                            accumulated by the move/turn steps)
//! change x by 5             (x -> 105)
//! change y by -10           (y -> 40)
//! point in direction 200    (normalizes to -160, real Scratch's own
//!                            (-180, 180] wrap)
//! set finalX to (x position of this sprite)   -- exercises motion_xposition
//! ```
//!
//! Every assertion below lands on a value produced by *plain arithmetic*
//! (goto_xy/change_by/the final direction wrap), not by `sin`/`cos` --
//! deliberately, so expected values are exact rather than needing a
//! floating-point tolerance for the trig steps earlier in the script (which
//! get fully overwritten by `goto_xy` before anything reads them).

use scratch_boring::{run_greenflag_and_report_json, run_greenflag_and_report_position_json};
use std::sync::Arc;

fn position(target: &'static str, axis: &'static str) -> f64 {
    let path: Arc<str> = Arc::from("assets/motion.json");
    run_greenflag_and_report_position_json(path, Arc::from(target), Arc::from(axis))
        .parse::<f64>()
        .unwrap_or_else(|_| panic!("expected a numeric position for {target}.{axis}"))
}

#[test]
fn goto_xy_and_change_by_land_on_exact_values() {
    assert_eq!(position("Sprite1", "x"), 105.0, "100 (goto_xy) + 5 (change_x_by)");
    assert_eq!(position("Sprite1", "y"), 40.0, "50 (goto_xy) - 10 (change_y_by)");
}

#[test]
fn point_in_direction_wraps_into_the_real_scratch_range() {
    // 200 is outside (-180, 180] -- real Scratch wraps it to -160, not 200.
    assert_eq!(position("Sprite1", "direction"), -160.0);
}

#[test]
fn xposition_reporter_reads_back_the_same_target_the_script_is_running_on() {
    let path: Arc<str> = Arc::from("assets/motion.json");
    // finalX was set via `data_setvariableto (x position of this sprite)`,
    // i.e. through motion_xposition + Frame.target_id, not a direct
    // position() call -- proves the reporter resolves to the *running*
    // sprite's own Positions entry, not some other/default target.
    let final_x: f64 = run_greenflag_and_report_json(path, Arc::from("finalX"))
        .parse()
        .unwrap();
    assert_eq!(final_x, 105.0);
}
