//! End-to-end test for the second round of Operators
//! (`operator_multiply`/`divide`/`mod`/`and`/`or`/`not`/`join`/
//! `letter_of`/`length`/`contains`/`mathop`) -- added once a real
//! scratch.mit.edu project (fetched to validate this project end to end)
//! showed these are among the single most common reporters in any
//! real-world project. Fixture generated by a small script (not checked
//! in) into `assets/operators.json` -- summarized script logic:
//!
//! ```text
//! when green flag clicked:
//!   mul_result           = 6 * 7                        -> 42
//!   div_result           = 10 / 4                        -> 2.5
//!   mod_result           = -7 mod 3                      -> 2   (floored, not truncated)
//!   mod_result2          = 7 mod -3                      -> -2  (sign follows the divisor)
//!   and_result           = (5 > 3) and (5 < 3)           -> false
//!   or_result            = (1 > 5) or (1 < 5)            -> true
//!   not_result           = not (1 > 5)                   -> true
//!   join_result          = join "foo" "bar"              -> "foobar"
//!   letter_result        = letter 2 of "hello"           -> "e"
//!   letter_oob_result    = letter 99 of "hello"          -> "" (out of range)
//!   length_result        = length of "hello"             -> 5
//!   contains_result      = "Hello World" contains "world"-> true (case-insensitive)
//!   contains_false_result= "Hello World" contains "xyz"  -> false
//!   abs_result           = abs(-5)                       -> 5
//!   floor_result         = floor(3.7)                    -> 3
//!   ceiling_result       = ceiling(3.2)                  -> 4
//!   sqrt_result          = sqrt(16)                       -> 4
//! ```

use scratch_boring::run_greenflag_and_report_json;
use std::sync::Arc;

#[test]
fn second_round_operators() {
    let path: Arc<str> = Arc::from("assets/operators.json");
    let get = |name: &'static str| run_greenflag_and_report_json(path.clone(), Arc::from(name));

    assert_eq!(get("mul_result").as_ref(), "42", "6 * 7");
    assert_eq!(get("div_result").as_ref(), "2.5", "10 / 4");
    assert_eq!(get("mod_result").as_ref(), "2", "-7 mod 3 is floored, not truncated (-7 % 3 == -1 in Rust)");
    assert_eq!(get("mod_result2").as_ref(), "-2", "7 mod -3 -- result takes the divisor's sign");
    assert_eq!(get("and_result").as_ref(), "false", "(5 > 3) and (5 < 3)");
    assert_eq!(get("or_result").as_ref(), "true", "(1 > 5) or (1 < 5)");
    assert_eq!(get("not_result").as_ref(), "true", "not (1 > 5)");
    assert_eq!(get("join_result").as_ref(), "foobar");
    assert_eq!(get("letter_result").as_ref(), "e", "1-based: letter 2 of \"hello\" is \"e\"");
    assert_eq!(get("letter_oob_result").as_ref(), "", "out-of-range index reports empty string, not an error");
    assert_eq!(get("length_result").as_ref(), "5");
    assert_eq!(get("contains_result").as_ref(), "true", "case-insensitive: \"world\" in \"Hello World\"");
    assert_eq!(get("contains_false_result").as_ref(), "false");
    assert_eq!(get("abs_result").as_ref(), "5");
    assert_eq!(get("floor_result").as_ref(), "3");
    assert_eq!(get("ceiling_result").as_ref(), "4");
    assert_eq!(get("sqrt_result").as_ref(), "4");
}
