//! End-to-end test for `operator_random`, ported directly from real
//! scratch-vm's own `operators.js` semantics -- see `BlockKind::Random`'s
//! `eval` case (`interpreter.br`) for the exact port. Fixture generated by
//! a small script (not checked in) into `assets/random.json`: summarized
//! script logic:
//!
//! ```text
//! when green flag clicked:
//!   repeat 30: add (pick random 1 to 6) to rolls
//!   equal_result    = pick random 5 to 5     -> 5 exactly, no randomness touched
//!   reversed_result = pick random 10 to 1    -> still in [1, 10], bounds auto-swapped
//!   float_result    = pick random 1.0 to 2.0 -> a float in [1.0, 2.0]
//! ```
//!
//! Real randomness can't be asserted on an exact value -- these tests
//! check statistical/structural properties instead (every roll lands in
//! range, *and* more than one distinct value actually appears over 30
//! rolls, which would fail if `Rng` were secretly a constant).

use scratch_boring::{run_greenflag_and_report_json, run_greenflag_and_report_list_json};
use std::collections::HashSet;
use std::sync::Arc;

#[test]
fn pick_random_die_rolls_stay_in_range_and_actually_vary() {
    let path: Arc<str> = Arc::from("assets/random.json");
    let contents = run_greenflag_and_report_list_json(path, Arc::from("rolls"));
    let rolls: Vec<i64> = contents
        .split(',')
        .map(|s| s.parse().expect("every roll should be a plain integer string"))
        .collect();

    assert_eq!(rolls.len(), 30);
    for &r in &rolls {
        assert!((1..=6).contains(&r), "roll {r} out of the requested [1, 6] range");
    }
    let distinct: HashSet<i64> = rolls.iter().copied().collect();
    assert!(
        distinct.len() > 1,
        "30 rolls of a 1-6 die landing on the exact same value every time (rolls: {rolls:?}) would mean Rng isn't actually varying"
    );
}

#[test]
fn pick_random_edge_cases() {
    let path: Arc<str> = Arc::from("assets/random.json");
    let get = |name: &'static str| run_greenflag_and_report_json(path.clone(), Arc::from(name));

    assert_eq!(get("equal_result").as_ref(), "5", "equal bounds return that value outright, no randomness touched");

    let reversed: f64 = get("reversed_result").parse().expect("plain number string");
    assert!((1.0..=10.0).contains(&reversed), "pick random 10 to 1 -- bounds must be auto-swapped, still [1, 10]");

    let float_result: f64 = get("float_result").parse().expect("plain number string");
    assert!(
        (1.0..=2.0).contains(&float_result),
        "pick random 1.0 to 2.0 -- a non-integer bound means a float result, not an integer one"
    );
}
