//! End-to-end test for `looks_sayforsecs`/`looks_thinkforsecs` -- the
//! single largest opcode left after `sensing_touchingobject` landed (see
//! README.md's "Status" section for the exact histogram numbers). Unlike
//! plain `looks_say`/`looks_think`, these span a tick boundary (set the
//! bubble, wait, clear the bubble) via the real pausable scheduler's
//! `WaitingUntilThenClearBubble` frame kind -- same multi-tick,
//! manual-`ScratchTimer.elapsed` technique `tests/scheduler.rs`'s own
//! `control_wait` test uses, since a script containing one of these can no
//! longer finish within a single tick in any observably-paused way.
//!
//! `assets/say_think_for_secs.json` (fixture generated by a small script,
//! not checked in) -- Sprite1's green-flag script:
//!
//! ```text
//! when green flag clicked:
//!   say "hello" for 1 secs
//!   think "done" for 1 secs
//! ```

use bevy::input::ButtonInput;
use bevy::prelude::*;
use scratch_boring::{
    play_queued_sounds, run_pending_threads, setup_scratch_project, sync_keyboard_state,
    sync_mouse_state, sync_scratch_timer, sync_speech_bubbles, ProjectPath, ScratchTimer,
    SpeechBubbleAnchor,
};
use std::sync::Arc;

fn test_app() -> App {
    let path: Arc<str> = Arc::from("assets/say_think_for_secs.json");
    let mut app = App::new();
    app.add_plugins(MinimalPlugins)
        .add_plugins((AssetPlugin::default(), ImagePlugin::default()))
        .insert_resource(ButtonInput::<KeyCode>::default())
        .insert_resource(ButtonInput::<MouseButton>::default())
        .insert_resource(ProjectPath { path })
        .add_systems(Startup, setup_scratch_project)
        .add_systems(
            Update,
            (
                sync_keyboard_state,
                sync_mouse_state,
                sync_scratch_timer,
                run_pending_threads,
                play_queued_sounds,
                sync_speech_bubbles,
            )
                .chain(),
        );
    app
}

fn bubble_text(app: &mut App) -> String {
    let world = app.world_mut();
    let mut query = world.query::<(&SpeechBubbleAnchor, &Text2d)>();
    let (_, text) = query
        .iter(world)
        .find(|(anchor, _)| anchor.target_id.as_ref() == "Sprite1")
        .expect("Sprite1 should have its own SpeechBubbleAnchor+Text2d child entity");
    text.0.to_string()
}

#[test]
fn say_then_think_for_secs_set_wait_and_clear_the_bubble_in_sequence() {
    let mut app = test_app();

    // Tick 1: the green-flag thread runs `say "hello" for 1 secs` --
    // the bubble is set immediately (a leaf side effect), then it parks
    // on the wait right there.
    app.update();
    assert_eq!(bubble_text(&mut app), "hello", "the say should have set the bubble before parking on the 1s wait");

    // A second tick with the timer still near 0 must NOT resolve the
    // wait -- the bubble stays exactly as it was.
    app.update();
    assert_eq!(bubble_text(&mut app), "hello", "1 second hasn't passed yet, the bubble must still be showing");

    // Push the timer past the 1s threshold: the say's wait resolves,
    // clearing the bubble -- and since there's no yield between that and
    // the very next statement, `think "done" for 1 secs` runs in this
    // same tick too, immediately overwriting the just-cleared bubble.
    app.world_mut().resource_mut::<ScratchTimer>().elapsed = 1.5;
    app.update();
    assert_eq!(bubble_text(&mut app), "done", "the say's wait should have resolved and the think should have run in the same tick, same as a plain `wait` followed by a non-yielding statement");

    // Another tick before the second wait's own threshold (1.5 + 1 = 2.5)
    // -- the bubble must still show "done".
    app.update();
    assert_eq!(bubble_text(&mut app), "done", "the think's own 1s wait hasn't elapsed yet");

    // Push the timer past the think's own threshold: its wait resolves
    // and clears the bubble, and there's nothing left in the script.
    app.world_mut().resource_mut::<ScratchTimer>().elapsed = 3.0;
    app.update();
    assert_eq!(bubble_text(&mut app), "", "the think's wait should have resolved and cleared the bubble, with no more script left to run");
}
