//! End-to-end test for the real pausable scheduler's three new stack
//! blocks -- `control_wait`, `control_forever`, `control_wait_until` --
//! landed together with `Thread`/`FrameKind`/`step_thread` (see either's
//! own doc comment in `runtime.br`/`interpreter.br` for the design).
//! Fixtures generated by a small script (not checked in) into
//! `assets/wait.json`/`assets/forever.json`/`assets/wait_until.json`:
//!
//! ```text
//! wait.json:       when green flag clicked: set x to 1; wait 1; set x to 2
//! forever.json:    when green flag clicked: forever: change counter by 1
//! wait_until.json: when green flag clicked: set result to "waiting";
//!                  wait until (timer > 1); set result to "done"
//! ```
//!
//! All three need a real Bevy `App` driven across multiple ticks -- unlike
//! every fixture before this one, a script containing one of these three
//! blocks can no longer finish within a single `run_greenflag_and_report*`
//! headless call in any observably-paused way (the headless path still
//! drives a thread all the way to completion in one shot -- see
//! `run_script`'s own doc comment -- so it can only ever show the *final*
//! state, never a genuinely mid-wait one).

use bevy::input::ButtonInput;
use bevy::prelude::*;
use scratch_boring::{
    play_queued_sounds, run_pending_threads, setup_scratch_project, stage_var_value,
    sync_keyboard_state, sync_mouse_state, sync_scratch_timer, ProjectPath, ScratchTimer, Vars,
};
use std::sync::Arc;

fn test_app(path: &str) -> App {
    let path: Arc<str> = Arc::from(path);
    let mut app = App::new();
    app.add_plugins(MinimalPlugins)
        .add_plugins((AssetPlugin::default(), ImagePlugin::default()))
        .insert_resource(ButtonInput::<KeyCode>::default())
        .insert_resource(ButtonInput::<MouseButton>::default())
        .insert_resource(ProjectPath { path })
        .add_systems(Startup, setup_scratch_project)
        .add_systems(
            Update,
            (
                sync_keyboard_state,
                sync_mouse_state,
                sync_scratch_timer,
                run_pending_threads,
                play_queued_sounds,
            )
                .chain(),
        );
    app
}

fn var_value(app: &mut App, fixture: &str, name: &'static str) -> String {
    let vars = app.world().resource::<Vars>().clone();
    stage_var_value(Arc::from(fixture), vars, Arc::from(name)).to_string()
}

#[test]
fn control_wait_pauses_the_thread_until_the_duration_elapses() {
    let mut app = test_app("assets/wait.json");

    // Tick 1: the green-flag thread runs `set x to 1`, then hits `wait 1`
    // -- a real yield point, so it pauses right there. `x` must already be
    // `1` (the statement before the wait genuinely ran), not `0`.
    app.update();
    assert_eq!(var_value(&mut app, "assets/wait.json", "x"), "1", "the statement before `wait` should have run");

    // A second tick with the timer still near 0 must NOT resolve the
    // wait -- `x` stays `1`.
    app.update();
    assert_eq!(var_value(&mut app, "assets/wait.json", "x"), "1", "1 second hasn't passed yet, the thread must still be waiting");

    // Push the timer past the 1-second threshold (same direct-`elapsed`
    // technique `tests/timer.rs` uses, see its own doc comment for why not
    // `Time::advance_by`), then tick: the wait resolves and `set x to 2`
    // finally runs.
    app.world_mut().resource_mut::<ScratchTimer>().elapsed = 1.5;
    app.update();
    assert_eq!(var_value(&mut app, "assets/wait.json", "x"), "2", "1.5s has passed the 1s wait, the thread should have resumed and finished");
}

#[test]
fn control_forever_yields_exactly_once_per_iteration() {
    let mut app = test_app("assets/forever.json");

    // Real Scratch's own `forever`/`repeat`/`repeat until` blocks yield
    // unconditionally at the end of every iteration (scratch-vm's own
    // block implementations call `util.yield()` every time, not gated on
    // a work-time budget -- that budget only bounds how many *different
    // threads* get a turn per tick, never how many iterations a single
    // thread's own loop gets) -- so N ticks must mean exactly N increments,
    // never more (a `forever` that ran to some huge iteration count within
    // one tick would be a real bug, not just imprecision).
    for i in 1..=5 {
        app.update();
        assert_eq!(
            var_value(&mut app, "assets/forever.json", "counter"),
            i.to_string(),
            "tick {i} should mean exactly {i} loop iterations, no more, no fewer"
        );
    }
}

#[test]
fn control_wait_until_re_checks_its_condition_every_tick() {
    let mut app = test_app("assets/wait_until.json");

    // Tick 1: `set result to "waiting"` runs, then `wait until (timer >
    // 1)` -- false at the start (timer is ~0), so the thread pauses there.
    app.update();
    assert_eq!(var_value(&mut app, "assets/wait_until.json", "result"), "waiting");

    // Still false on another tick with the timer left near 0.
    app.update();
    assert_eq!(var_value(&mut app, "assets/wait_until.json", "result"), "waiting", "timer is still under 1, the condition hasn't flipped yet");

    // Push the timer past the threshold, then tick: the condition is now
    // true, so the wait resolves and `set result to "done"` runs.
    app.world_mut().resource_mut::<ScratchTimer>().elapsed = 1.5;
    app.update();
    assert_eq!(var_value(&mut app, "assets/wait_until.json", "result"), "done");
}
