//! End-to-end test for `sound_setvolumeto`/`sound_changevolumeby` --
//! applied once, at spawn time, onto the real `PlaybackSettings.volume`
//! of the `AudioPlayer` entity `sound_play` triggers (`SoundQueue.
//! volumes`' own doc comment in runtime.br explains why volume lives on
//! `SoundQueue` itself rather than its own resource: `run_pending_
//! threads` was already at Bevy's hard 16-parameter `SystemParam` limit).
//!
//! Uses `assets/sound_volume_test.sb3` (a real zip with one genuine
//! minimal WAV sound, same technique `tests/sound_ecs.rs`'s own
//! `sound_test.sb3` fixture already uses, generated by a small script not
//! checked in):
//!
//! ```text
//! Sprite1, when green flag clicked:
//!   set volume to 80
//!   change volume by 1000        -> 80 + 1000 = 1080, clamped to 100
//!   play sound "beep"
//! ```

use bevy::audio::AudioPlugin;
use bevy::input::ButtonInput;
use bevy::prelude::*;
use scratch_boring::{play_queued_sounds, run_pending_threads, setup_scratch_project, sync_keyboard_state, sync_mouse_state, ProjectPath};
use std::sync::Arc;

#[test]
fn sound_play_applies_the_clamped_current_volume_to_the_real_playback_settings() {
    let path: Arc<str> = Arc::from("assets/sound_volume_test.sb3");
    let mut app = App::new();
    app.add_plugins(MinimalPlugins)
        .add_plugins((AssetPlugin::default(), ImagePlugin::default(), AudioPlugin::default()))
        .insert_resource(ButtonInput::<KeyCode>::default())
        .insert_resource(ButtonInput::<MouseButton>::default())
        .insert_resource(ProjectPath { path })
        .add_systems(Startup, setup_scratch_project)
        .add_systems(
            Update,
            (sync_keyboard_state, sync_mouse_state, run_pending_threads, play_queued_sounds).chain(),
        );

    // One tick: the green-flag script sets volume to 80, changes it by
    // 1000 (clamped to 100), then plays -- all leaf statements, no wait
    // involved, so the whole script (and play_queued_sounds draining the
    // resulting request into a real entity) finishes within this tick.
    app.update();

    let world = app.world_mut();
    let mut query = world.query::<&PlaybackSettings>();
    let settings = query
        .iter(world)
        .next()
        .expect("sound_play should have spawned one entity with real PlaybackSettings");
    let linear = settings.volume.to_linear();
    assert!((linear - 1.0).abs() < 0.001, "80 + 1000 clamped to 100 -> full linear volume (1.0), got {linear}");
}
