//! End-to-end test for the full Sound pipeline through the real Bevy
//! scheduler: `sound_play` queues a request, `play_queued_sounds` spawns a
//! real `PlayingSound`/`AudioPlayer` entity from it, and
//! `sound_stopallsounds` (triggered here via an `event_whenkeypressed`
//! hat, exercising two Phase 2 features together) despawns it again.
//!
//! Uses `assets/sound_test.sb3` (generated by a small script, not checked
//! in): a real zip with one genuine minimal WAV sound (Sprite1's "beep"),
//! since `tests/sounds.rs` already covers the low-level extraction
//! function directly and this test needs the full pipeline, including a
//! real asset the `AudioPlugin` can actually load.
//!
//! ```text
//! Sprite1, when green flag clicked:  play sound "beep"
//! Sprite1, when space key pressed:   stop all sounds
//! ```

use bevy::audio::AudioPlugin;
use bevy::input::ButtonInput;
use bevy::prelude::*;
use scratch_boring::{
    check_key_press_hats, play_queued_sounds, run_pending_threads, setup_scratch_project,
    sync_keyboard_state, sync_mouse_state, PlayingSound, ProjectPath,
};
use std::sync::Arc;

fn test_app() -> App {
    let path: Arc<str> = Arc::from("assets/sound_test.sb3");
    let mut app = App::new();
    app.add_plugins(MinimalPlugins)
        .add_plugins((AssetPlugin::default(), ImagePlugin::default(), AudioPlugin::default()))
        .insert_resource(ButtonInput::<KeyCode>::default())
        .insert_resource(ButtonInput::<MouseButton>::default())
        .insert_resource(ProjectPath { path })
        .add_systems(Startup, setup_scratch_project)
        .add_systems(
            Update,
            (
                sync_keyboard_state,
                sync_mouse_state,
                check_key_press_hats,
                run_pending_threads,
                play_queued_sounds,
            )
                .chain(),
        );
    app
}

fn playing_sound_count(app: &mut App) -> usize {
    let world = app.world_mut();
    let mut query = world.query::<&PlayingSound>();
    query.iter(world).count()
}

#[test]
fn sound_play_spawns_a_playing_sound_entity_and_stopallsounds_despawns_it() {
    let mut app = test_app();

    // Tick 1: Startup queues the green-flag script; the same tick's
    // run_pending_threads runs it (sound_play queues a SoundRequest), and
    // play_queued_sounds (chained right after) drains that request into a
    // real spawned entity, all within this one `app.update()` call.
    app.update();
    assert_eq!(
        playing_sound_count(&mut app),
        1,
        "sound_play should have spawned exactly one PlayingSound entity"
    );

    // Press space: the "when space key pressed -> stop all sounds" hat
    // should fire this tick, and play_queued_sounds should despawn the
    // still-playing entity from tick 1 in the same tick.
    app.world_mut()
        .resource_mut::<ButtonInput<KeyCode>>()
        .press(KeyCode::Space);
    app.update();

    assert_eq!(
        playing_sound_count(&mut app),
        0,
        "sound_stopallsounds should have despawned every PlayingSound entity"
    );
}
