//! End-to-end test for `sensing_timer` and the `event_whengreaterthan`
//! (TIMER) hat -- the feature this session's research into scratch-vm's
//! own official test suite (`scratchfoundation/scratch-vm`, AGPLv3,
//! `test/fixtures/edge-triggered-hat.sb3` -- not vendored into this repo,
//! see README.md) directly motivated: that fixture's own script is
//! `when timer > -1: move 10 steps`, which only makes sense as a real,
//! edge-triggered "fires once at frame 0, never again" test once
//! `sensing_timer`/`event_whengreaterthan` exist at all.
//!
//! Fixture generated by a small script (not checked in) into
//! `assets/timer.json`:
//!
//! ```text
//! Sprite1, when timer > 0.05:  change fireCount by 1
//! ```
//!
//! `ScratchTimer.elapsed` is set directly here rather than via
//! `Time::advance_by` -- `MinimalPlugins`' own `TimePlugin` updates the
//! generic `Res<Time>` from real wall-clock elapsed time each frame
//! regardless, so a manually `advance_by`'d value isn't reliably what
//! `sync_scratch_timer` sees on the next tick (confirmed with a real test
//! run: injecting 100ms this way produced a `delta_secs()` of only ~2.4ms,
//! not 100ms). Setting `ScratchTimer.elapsed` directly sidesteps that
//! entirely -- `sync_scratch_timer` still runs and adds its own (tiny,
//! real-wall-clock) delta on top each tick, which is harmless here since
//! every assertion below only cares about crossing the 0.05 threshold, not
//! an exact value.

use bevy::input::ButtonInput;
use bevy::prelude::*;
use scratch_boring::{
    check_greater_than_hats, play_queued_sounds, run_greenflag_and_report_json,
    run_pending_threads, setup_scratch_project, stage_var_value, sync_keyboard_state,
    sync_mouse_state, sync_scratch_timer, ProjectPath, ScratchTimer, Vars,
};
use std::sync::Arc;

/// `assets/timer.json` also has a green-flag script (`set timerAtStart to
/// (timer)`) purely to exercise this headless-only limitation: with no
/// real Bevy `Time` to ever advance it, `sensing_timer` can only honestly
/// report the value it starts at, `0`, in this pure headless call path --
/// see `ScratchTimer`'s own doc comment for why that's a documented
/// limitation, not a bug.
#[test]
fn sensing_timer_headless_always_reports_the_starting_zero() {
    let path: Arc<str> = Arc::from("assets/timer.json");
    let value = run_greenflag_and_report_json(path, Arc::from("timerAtStart"));
    assert_eq!(value.as_ref(), "0");
}

fn test_app() -> App {
    let path: Arc<str> = Arc::from("assets/timer.json");
    let mut app = App::new();
    app.add_plugins(MinimalPlugins)
        .add_plugins((AssetPlugin::default(), ImagePlugin::default()))
        .insert_resource(ButtonInput::<KeyCode>::default())
        .insert_resource(ButtonInput::<MouseButton>::default())
        .insert_resource(ProjectPath { path })
        .add_systems(Startup, setup_scratch_project)
        .add_systems(
            Update,
            (
                sync_keyboard_state,
                sync_mouse_state,
                sync_scratch_timer,
                check_greater_than_hats,
                run_pending_threads,
                play_queued_sounds,
            )
                .chain(),
        );
    app
}

fn fire_count(app: &mut App) -> String {
    let vars = app.world().resource::<Vars>().clone();
    stage_var_value(Arc::from("assets/timer.json"), vars, Arc::from("fireCount")).to_string()
}

#[test]
fn greater_than_hat_fires_exactly_once_on_the_tick_it_crosses_the_threshold() {
    let mut app = test_app();

    // Tick 1: Startup runs; ScratchTimer starts at 0.0, well under the
    // 0.05 threshold, so the hat must not have fired yet.
    app.update();
    assert_eq!(fire_count(&mut app), "0", "timer starts at 0, below the 0.05 threshold");

    // Push the timer past the threshold directly (see module doc comment
    // for why not via Time::advance_by), then tick: the hat should fire
    // exactly once.
    app.world_mut().resource_mut::<ScratchTimer>().elapsed = 0.1;
    app.update();
    assert_eq!(fire_count(&mut app), "1", "timer should have crossed 0.05 and fired once");

    // Still well past the threshold on the next tick too -- must NOT
    // re-fire (edge-triggered, not level-triggered).
    app.update();
    assert_eq!(fire_count(&mut app), "1", "must not re-fire while the condition stays true");
}
