//! End-to-end test for `sensing_touchingobject` (sprite-to-sprite, mouse,
//! and stage-edge touching) -- the single largest opcode left after
//! costume switching landed, per the same opcode-histogram check that's
//! driven every round since the scheduler (see README.md's "Status"
//! section for the exact numbers).
//!
//! This project's `Touching` is a real, if simplified, AABB (axis-
//! aligned bounding box) overlap test -- not real Scratch's own pixel-
//! perfect alpha-channel test. See `runtime.br`'s `BlockKind::Touching`
//! and `aabb_overlap`/`touching_point`/`touching_stage_edge` doc comments
//! for why that's an honest trade for this project today (it doesn't
//! apply sprite rotation to its own rendering yet either, so there's no
//! rotated bounding box this approximation is *failing* to account for).
//!
//! `assets/touching_sprites.json`/`assets/touching_hidden.json` (fixtures
//! generated by a small script, not checked in) are raw-JSON projects with
//! no real `.sb3` costume assets -- `TargetCostumeDims` falls back to its
//! 40x40 placeholder box for every sprite here (see that struct's own doc
//! comment in runtime.br), so every expected value below is derived from
//! that fixed, known footprint, not a guessed real-asset size.
//! `tests/touching_real_costume.rs` (sibling file) is where a real `.sb3`'s
//! actual pixel dimensions get exercised instead.

use scratch_boring::run_greenflag_and_report_json;
use std::sync::Arc;

#[test]
fn touching_sprite_mouse_and_edge_all_use_the_same_aabb_math() {
    let path: Arc<str> = Arc::from("assets/touching_sprites.json");
    let get = |name: &'static str| run_greenflag_and_report_json(path.clone(), Arc::from(name));

    // A@(0,0), B@(30,0), both 40x40 (half-width 20 each) -> touching
    // threshold |dx| < 40. dx=30 -> true.
    assert_eq!(get("touch_initial").as_ref(), "true", "A at (0,0) should be touching B at (30,0) -- |dx|=30 < 40");
    // A moves to (100,0) -- dx=70 >= 40 -> no longer touching.
    assert_eq!(get("touch_after_move").as_ref(), "false", "A at (100,0) should no longer be touching B at (30,0) -- |dx|=70 >= 40");
    // A moves back to (0,0); headless mouse is always fixed at (0,0) --
    // A's own box [-20,20]x[-20,20] contains the mouse point.
    assert_eq!(get("touch_mouse_at_origin").as_ref(), "true", "A back at (0,0) should be touching the (headless-fixed) mouse at (0,0)");
    // A moves to (300,0) -- box [280,320] extends past the real 240 stage edge.
    assert_eq!(get("touch_edge_far").as_ref(), "true", "A at (300,0) (box [280,320]) should be touching the stage edge (240)");
    // A moves back to (0,0) -- box [-20,20], well within [-240,240].
    assert_eq!(get("touch_edge_center").as_ref(), "false", "A at (0,0) should not be touching the stage edge");
}

#[test]
fn a_hidden_sprite_never_touches_and_is_never_touched() {
    // Real scratch-vm's own `isTouchingSprite`: checked before any
    // position/size math at all. A and B exactly overlap here (both at
    // (0,0)) -- if visibility weren't checked, this would report `true`.
    let path: Arc<str> = Arc::from("assets/touching_hidden.json");
    let out = run_greenflag_and_report_json(path, Arc::from("touch_hidden"));
    assert_eq!(out.as_ref(), "false", "B is visible=false in the fixture -- A must not report touching it even though they exactly overlap");
}
