//! End-to-end test for `data_showvariable`/`data_hidevariable` --
//! dynamically toggling a variable watcher's visibility at runtime, on
//! top of the static per-monitor visibility `tests/watchers.rs` already
//! covers. `assets/watcher_visibility.json` (fixture generated by a
//! small script, not checked in): two Stage variables, `a` (monitor
//! starts hidden) and `b` (monitor starts visible); Sprite1's own
//! green-flag script:
//!
//! ```text
//! show variable "a"   -> a's watcher entity flips to Visibility::Visible
//! hide variable "b"   -> b's watcher entity flips to Visibility::Hidden
//! ```

use bevy::input::ButtonInput;
use bevy::prelude::*;
use scratch_boring::{
    play_queued_sounds, run_pending_threads, setup_scratch_project, sync_keyboard_state,
    sync_mouse_state, sync_variable_watchers, ProjectPath, VariableWatcherTag,
};
use std::sync::Arc;

#[test]
fn show_and_hide_variable_flip_the_real_watcher_visibility_component() {
    let path: Arc<str> = Arc::from("assets/watcher_visibility.json");
    let mut app = App::new();
    app.add_plugins(MinimalPlugins)
        .add_plugins((AssetPlugin::default(), ImagePlugin::default()))
        .insert_resource(ButtonInput::<KeyCode>::default())
        .insert_resource(ButtonInput::<MouseButton>::default())
        .insert_resource(ProjectPath { path })
        .add_systems(Startup, setup_scratch_project)
        .add_systems(
            Update,
            (sync_keyboard_state, sync_mouse_state, run_pending_threads, play_queued_sounds, sync_variable_watchers).chain(),
        );

    // Both blocks are leaf statements (no wait involved), so the whole
    // script finishes within this one tick.
    app.update();

    let world = app.world_mut();
    let mut query = world.query::<(&VariableWatcherTag, &Visibility)>();
    let mut found: Vec<(String, bool)> = query
        .iter(world)
        .map(|(tag, vis)| (tag.label.to_string(), *vis == Visibility::Visible))
        .collect();
    found.sort();

    assert_eq!(found.len(), 2, "both variables should have their own watcher entity, got: {found:?}");
    assert_eq!(found[0], ("a".to_string(), true), "\"show variable a\" should flip a's watcher to visible, even though its monitor started hidden");
    assert_eq!(found[1], ("b".to_string(), false), "\"hide variable b\" should flip b's watcher to hidden, even though its monitor started visible");
}
